export enum APP_ROUTER_PATHS {
  MAIN = '/',
  FAQ = '/faq',
  STRATEGIES = '/strategies',
  SUPPORT = '/support',
  PRIVACY = '/privacy',
  USER_ACCOUNTS = '/user/accounts',
  USER_BILLS = '/user/bills',
  USER_FAQ = '/user/faq',
  USER_SUPPORT = '/user/support',
  USER_SETTINGS = '/user/settings',
  USER_STRATEGIES = '/user/strategies',
  ADMIN_ACCOUNTS = '/admin/accounts',
  ADMIN_STRATEGIES = '/admin/strategies',
  ADMIN_PAYMENTS = '/admin/payments',
  ADMIN_SETTINGS = '/admin/settings',
}
